# 服务端口号
server:
  port: 9098

# 是否启用Swagger
swagger:
  enable: true

# 配置数据库
spring:
  application:
    name: demo-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.84.93:3306/troucker?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: YEIG
    password: 123456

# 配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描
  type-aliases-package: com.ruanyangyang.demo.entity
  # 逻辑删除配置 1删除 0未删除
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0